### ISSUE TITLE
What are the use cases for disabling a task?

### ISSUE THREAD

**Issue by wpscholar** [newfold-labs/wp-module-tasks#7]
Is there a reason we would disable a task as opposed to just deleting it?

If not, we should remove the `enabled` column from the database as well as any class properties, etc.

**Comment by amartya-dev** [comment]
It was added for a use case related to periodic tasks, this will allow a user to disable a periodic task and re-enable when needed without having to re-create the task from scratch.

So our system would only delete the cron entry and re-add it when the task is enabled again.
